// Existing SVGs
export { CameraHero, default as CameraHeroDefault } from './CameraHero'
export { ViewfinderScanFrame, default as ViewfinderScanFrameDefault } from './ViewfinderScanFrame'
export { KeyIcon, default as KeyIconDefault } from './KeyIcon'
export { CameraAvatar, GhostAvatar } from './PlayerAvatars'
export { TimerRing, default as TimerRingDefault } from './TimerRing'
export { PolaroidFrame, default as PolaroidFrameDefault } from './PolaroidFrame'
export { CheckmarkStamp, default as CheckmarkStampDefault } from './CheckmarkStamp'
export { default as WinnerMedal, default as WinnerMedalDefault } from './WinnerMedal'
export { default as FilmStrip, default as FilmStripDefault } from './FilmStrip'
export { default as EmptyPolaroid, default as EmptyPolaroidDefault } from './EmptyPolaroid'
export { default as BrokenViewfinder, default as BrokenViewfinderDefault } from './BrokenViewfinder'

// New SVGs
export { SlidersIcon, default as SlidersIconDefault } from './SlidersIcon'
export { StopwatchIcon, default as StopwatchIconDefault } from './StopwatchIcon'
export { PeopleDotsIcon, default as PeopleDotsIconDefault } from './PeopleDotsIcon'
export { CompassIcon, default as CompassIconDefault } from './CompassIcon'
export { RoundCounterIcon, default as RoundCounterIconDefault } from './RoundCounterIcon'
export { HostCrownBadge, default as HostCrownBadgeDefault } from './HostCrownBadge'
export { default as TargetColorCard, default as TargetColorCardDefault } from './TargetColorCard'
export { default as ReadyCheckIcon, default as ReadyCheckIconDefault } from './ReadyCheckIcon'
export { default as FoundIcon, default as FoundIconDefault } from './FoundIcon'
export { default as MissedIcon, default as MissedIconDefault } from './MissedIcon'
export { default as ConfettiBurst, default as ConfettiBurstDefault } from './ConfettiBurst'
export { default as SplashAperture, default as SplashApertureDefault } from './SplashAperture'
export { FlatLogoMark, default as FlatLogoMarkDefault } from './FlatLogoMark'
export { SpectrumLensLogo, default as SpectrumLensLogoDefault } from './SpectrumLensLogo'
export { ShareIcon, default as ShareIconDefault } from './ShareIcon'
export { CopyIcon, default as CopyIconDefault } from './CopyIcon'
